import React, { useEffect, useState } from 'react';

export default function AdminPage({ Brand, api, logout, go }) {
  const [data, setData] = useState({ classes: [], teachers: [] }); const [message, setMessage] = useState(''); const [toast, setToast] = useState(''); const [editingClass, setEditingClass] = useState(null);
  const load = () => api('/api/catalog/management/options').then(setData).catch((e) => setMessage(e.message)); useEffect(load, []);
  const createTeacher = async (e) => { e.preventDefault(); const formElement = e.currentTarget; const form = new FormData(formElement); try { await api('/api/auth/teachers', { method: 'POST', body: JSON.stringify({ fullName: form.get('fullName'), email: form.get('email'), password: form.get('password') }) }); formElement.reset(); setMessage(''); setToast('Tài khoản giáo viên đã được tạo và có thể đăng nhập.'); load(); } catch (e) { setMessage(e.message); } };
  const createClass = async (e) => { e.preventDefault(); const formElement = e.currentTarget; const form = new FormData(formElement); try { await api('/api/catalog/classes', { method: 'POST', body: JSON.stringify({ name: form.get('name'), grade: form.get('grade'), teacher_id: form.get('teacher_id') || null }) }); formElement.reset(); setMessage('Đã tạo lớp.'); load(); } catch (e) { setMessage(e.message); } };
  const updateClass = async (e) => { e.preventDefault(); const formElement = e.currentTarget; const form = new FormData(formElement); try { await api(`/api/catalog/classes/${editingClass.id}`, { method: 'PUT', body: JSON.stringify({ name: form.get('name'), grade: form.get('grade'), teacher_id: form.get('teacher_id') || null }) }); setEditingClass(null); setMessage('Đã cập nhật lớp và giáo viên phụ trách.'); load(); } catch (e) { setMessage(e.message); } };
  const addMember = async (e) => { e.preventDefault(); const formElement = e.currentTarget; const form = new FormData(formElement); try { await api('/api/catalog/classes/members', { method: 'POST', body: JSON.stringify({ class_id: form.get('class_id'), email: form.get('email') }) }); formElement.reset(); setMessage('Đã thêm học sinh vào lớp.'); } catch (e) { setMessage(e.message); } };
  const stats = [
    ['Tổng người dùng', '1,248', '+12.4%', '👥', 'blue'],
    ['Giáo viên', '86', '+6.2%', '🎓', 'violet'],
    ['Học sinh', '1,024', '+13.7%', '🎒', 'green'],
    ['Lớp học', '42', '+4.8%', '🏫', 'purple'],
    ['Bài tập đã tạo', '386', '+15.3%', '📝', 'yellow'],
    ['Tỷ lệ hoạt động', '91%', '+5.6%', '⌁', 'teal']
  ];
  const activity = [
    ['19/06/2024 10:23', 'Tạo lớp học', 'Nguyễn Thị Lan', 'Lớp 3A', 'Tạo mới lớp 3A năm học 2024-2025', 'green'],
    ['19/06/2024 09:15', 'Giao bài tập', 'Trần Văn Minh', 'Lớp 4B', 'Giao bài “Phép cộng trong phạm vi 100”', 'blue'],
    ['18/06/2024 16:42', 'Tạo tài khoản giáo viên', 'Admin', 'Phạm Thu Hà', 'Tạo tài khoản giáo viên mới', 'blue'],
    ['18/06/2024 11:08', 'Cảnh báo', 'Hệ thống', 'Lớp 5C', 'Tỷ lệ hoàn thành bài tập thấp (32%)', 'orange'],
    ['17/06/2024 14:33', 'Tạo lớp học', 'Lê Quang Huy', 'Lớp 2D', 'Tạo mới lớp 2D năm học 2024-2025', 'green']
  ];
  const subjects = [['Toán', 98], ['Tiếng Việt', 87], ['Tiếng Anh', 76], ['Khoa học', 58], ['Lịch sử & địa lý', 39], ['Tin học', 28]];
  return <main className="admin-dashboard">
    <aside className="admin-sidebar">
      <Brand href="/admin" go={go} /><div className="sidebar-school">CỔNG QUẢN LÝ NHÀ TRƯỜNG</div>
      {['▦  Tổng quan', '♙  Người dùng', '◇  Giáo viên', '☺  Học sinh', '♧  Phụ huynh', '▤  Lớp học', '▥  Môn học & Chủ đề', '▣  Bài tập', '◫  Phân tích hệ thống', '✧  AI & Mô hình', '♧  Thông báo', '⚙  Cài đặt'].map((item, index) => <button className={`sidebar-item ${index === 0 ? 'active' : ''}`} type="button" key={item}>{item}{item.includes('Thông báo') && <b>8</b>}</button>)}
      <button className="sidebar-logout" type="button" onClick={logout}>↪ Đăng xuất</button>
    </aside>
    <section className="admin-main">
      <header className="dashboard-header"><div><span className="eyebrow">TỔNG QUAN HỆ THỐNG</span><h1>Dashboard quản lý</h1><p>Theo dõi hoạt động và hiệu quả toàn hệ thống</p></div><div className="dashboard-actions"><button type="button">▣  30 ngày qua⌄</button><button type="button">⌖  Toàn hệ thống⌄</button><button className="dashboard-primary" type="button" onClick={() => document.getElementById('quick-management')?.scrollIntoView({ behavior: 'smooth' })}>＋ Tạo tài khoản</button></div></header>
      <div className="dashboard-stats">{stats.map(([label, value, trend, icon, color]) => <article className="dashboard-stat" key={label}><span className={`stat-icon ${color}`}>{icon}</span><div><small>{label}</small><strong>{value}</strong><em>↑ {trend} so với 30 ngày trước</em></div></article>)}</div>
      <div className="dashboard-grid dashboard-charts">
        <section className="dashboard-card activity-chart"><h2>Số người dùng hoạt động theo tuần</h2><div className="line-chart"><div className="chart-y"><span>1,500</span><span>1,200</span><span>900</span><span>300</span><span>0</span></div><svg viewBox="0 0 620 220" role="img" aria-label="Biểu đồ người dùng hoạt động"><path className="chart-area" d="M35 168 L145 151 L250 128 L350 104 L450 77 L535 54 L600 29 L600 190 L35 190 Z" /><polyline points="35,168 145,151 250,128 350,104 450,77 535,54 600,29" /><g>{[[35,168,'782'],[145,151,'812'],[250,128,'905'],[350,104,'1,012'],[450,77,'1,089'],[535,54,'1,176'],[600,29,'1,248']].map(([x, y, value]) => <g key={x}><circle cx={x} cy={y} r="5" /><text x={x} y={y - 12}>{value}</text></g>)}</g></svg><div className="chart-x"><span>15/04-21/04</span><span>22/04-28/04</span><span>29/04-05/05</span><span>06/05-12/05</span><span>13/05-19/05</span><span>20/05-26/05</span><span>27/05-02/06</span></div></div><div className="chart-legend"><i /> Người dùng hoạt động</div></section>
        <section className="dashboard-card subject-chart"><h2>Số bài tập theo môn học</h2><div className="bar-chart">{subjects.map(([label, value]) => <div className="bar-item" key={label}><span>{value}</span><i style={{ height: `${value}%` }} /><small>{label}</small></div>)}</div></section>
        <section className="dashboard-card role-chart"><h2>Phân bổ vai trò người dùng</h2><div className="donut-wrap"><div className="donut"><strong>1,248</strong><small>Tổng</small></div><ul><li><i className="dot green" />Học sinh <b>1,024 (82.1%)</b></li><li><i className="dot blue" />Giáo viên <b>86 (6.9%)</b></li><li><i className="dot yellow" />Phụ huynh <b>110 (8.8%)</b></li><li><i className="dot purple" />Quản trị viên <b>28 (2.2%)</b></li></ul></div></section>
        <section className="dashboard-card module-chart"><h2>Mức độ sử dụng các module</h2>{[['Bài tập', 92], ['Phân tích học tập', 78], ['AI & Gợi ý', 65], ['Thông báo', 58], ['Báo cáo', 54], ['Quản lý lớp học', 88]].map(([label, value]) => <div className="module-row" key={label}><span>{label}</span><div><i style={{ width: `${value}%` }} /></div><b>{value}%</b></div>)}</section>
      </div>
      <div className="dashboard-grid dashboard-bottom">
        <section className="dashboard-card recent-card"><div className="card-heading"><h2>Hoạt động gần đây</h2><button type="button">Xem tất cả →</button></div><div className="activity-table"><div className="activity-table-head"><span>Thời gian</span><span>Sự kiện</span><span>Người thực hiện</span><span>Đối tượng</span><span>Chi tiết</span></div>{activity.map(([time, event, actor, target, detail, color]) => <div className="activity-row" key={`${time}-${event}`}><span>{time}</span><span><i className={`event-dot ${color}`} />{event}</span><span>{actor}</span><span>{target}</span><span>{detail}</span></div>)}</div></section>
        <section className="dashboard-card alerts-card"><div className="card-heading"><h2>Cảnh báo hệ thống</h2><button type="button">Xem tất cả</button></div>{[['⚠', 'Lớp 5C có tỷ lệ hoàn thành bài tập thấp', 'Chỉ 32% học sinh hoàn thành trong 7 ngày qua', 'orange'], ['△', 'Chủ đề “Phân số” có kết quả thấp', 'Điểm trung bình của chủ đề thấp hơn mức bình thường', 'yellow'], ['!', 'Mô hình AI dự đoán kết quả cần xem xét', 'Độ chính xác của mô hình giảm 8% so với tuần trước', 'red']].map(([icon, title, detail, color]) => <article className={`alert-item ${color}`} key={title}><strong>{icon}</strong><div><b>{title}</b><small>{detail}</small></div><span>›</span></article>)}</section>
        <section className="dashboard-card analytics-card"><div><span>✧</span><small>AI & Learning Analytics</small><strong>24</strong><em>↑ 33% so với tuần trước</em></div><div className="analytics-spark">╱╲╱╱╱╱</div><button type="button">Xem chi tiết Analytics →</button></section>
      </div>
      {toast && <div className="success-modal-backdrop" role="status" onClick={() => setToast('')}><div className="success-modal" role="alert" onClick={(event) => event.stopPropagation()}><div className="success-check">✓</div><h2>Đăng ký thành công!</h2><p>{toast}</p><button type="button" onClick={() => setToast('')}>Đã hiểu</button></div></div>}
      <section className="dashboard-card quick-management" id="quick-management"><div className="card-heading"><div><h2>Quản lý nhanh</h2></div>{message && <span className="message">{message}</span>}</div><div className="grid"><section className="card"><h2>+ Tạo tài khoản giáo viên</h2><form onSubmit={createTeacher}><label>Họ tên giáo viên<input name="fullName" required minLength="2" /></label><label>Email<input name="email" type="email" required /></label><label>Mật khẩu tạm thời<input name="password" type="password" required minLength="6" /></label><button className="primary">Tạo tài khoản</button></form></section><section className="card"><h2>+ Tạo lớp học</h2><form onSubmit={createClass}><label>Tên lớp<input name="name" required /></label><label>Khối<input name="grade" required /></label><label>Giáo viên<select name="teacher_id"><option value="">Chưa chỉ định</option>{data.teachers.map((teacher) => <option value={teacher.id} key={teacher.id}>{teacher.full_name} · {teacher.email}</option>)}</select></label><button className="primary">Tạo lớp</button></form></section><section className="card"><h2>+ Thêm học sinh</h2><form onSubmit={addMember}><label>Lớp học<select name="class_id" required><option value="">Chọn lớp học</option>{data.classes.map((item) => <option value={item.id} key={item.id}>{item.name} · {item.grade}</option>)}</select></label><label>Email học sinh<input name="email" type="email" required /></label><button className="primary">Thêm vào lớp</button></form></section></div><div className="managed-classes"><div className="card-heading"><h2>Danh sách lớp cần quản lý</h2><span>{data.classes.length} lớp</span></div>{data.classes.map((item) => <article className="managed-class-row" key={item.id}><div><strong>{item.name} · {item.grade}</strong><small>Giáo viên: {item.assigned_teacher_name || 'Chưa chỉ định'}</small></div><button className="secondary-action" type="button" onClick={() => setEditingClass(item)}>Chỉnh sửa</button></article>)}</div>{editingClass && <div className="edit-class-panel"><div className="card-heading"><h2>Chỉnh sửa lớp học</h2><button className="secondary-action" type="button" onClick={() => setEditingClass(null)}>Đóng</button></div><form onSubmit={updateClass} className="edit-class-form"><label>Tên lớp<input name="name" defaultValue={editingClass.name} required /></label><label>Khối<input name="grade" defaultValue={editingClass.grade} required /></label><label>Giáo viên phụ trách<select name="teacher_id" defaultValue={editingClass.assigned_teacher_id || ''}><option value="">Chưa chỉ định</option>{data.teachers.map((teacher) => <option value={teacher.id} key={teacher.id}>{teacher.full_name} · {teacher.email}</option>)}</select></label><button className="primary" type="submit">Lưu thay đổi</button></form></div>}</section>
    </section>
  </main>;
}
